# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  building:
    name: build app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Reconfigure git to use HTTP authentication
      run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/

    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
